### ISSUE TITLE
Make GitHub organization 

### ISSUE THREAD

**Issue by cranmer** [everpub/openscienceprize#104]
Probably this is for later since time is tight, but perhaps something to clean up before submission....

Do we make an `everpub` organization now, move this repo there?
To avoid broken links @betatim could fork from organization.

**Comment by ctb** [comment]
On Mon, Feb 29, 2016 at 11:27:56AM -0800, Kyle Cranmer wrote:
> Probably this is for later since time is tight, but perhaps something to clean up before submission....
> 
> Do we make an `everpub` organization now, move this repo there?
> To avoid broken links @betatim could fork from organization.

http://github.com/everpub, @betatim is an owner.

**Comment by betatim** [comment]
I just got back home, need to make dinner and pickup the flat a bit. I
think github is smart enough to redirect all links if I move the repo. So I
would suggest to move the repo but not try and update all the links. At
least I won't have time to do so without missing some.

**Comment by cranmer** [comment]
All good to me
