### ISSUE TITLE
Journal contacts

### ISSUE THREAD

**Issue by betatim** [everpub/openscienceprize#22]
What should we ask from a journal if we make contact with them?

Move this thread of discussion here from #18

**Comment by ctb** [comment]
We can get "acknowledgement of interest" from GigaScience and/or PeerJ very quickly, I think. Nothing else would really be needed IMO.

**Comment by ctb** [comment]
Oh, and F1000Research.

**Comment by khinsen** [comment]
I am on the editorial board of [Computing in Science & Engineering](http://www.computer.org/web/computingnow/cise). If you think any support from there would help, I can ask. I don't really know what kind of support would be useful, however.

**Comment by betatim** [comment]
I would ask them: could you imagine using this? Would you be interested in seeing a working demo of it? Similar to the "acknowledgement of interest"

**Comment by khinsen** [comment]
OK, I'll send a link to this document to the editorial board mailing list and ask for comments.

**Comment by betatim** [comment]
:+1:

**Comment by cranmer** [comment]
Not sure what the attitudes are here about:
http://cogentoa.tandfonline.com

http://www.journals.elsevier.com/softwarex/

http://www.journals.elsevier.com/computer-physics-communications/

but I have connections with their editors. The first two are still in the formative stages

**Comment by betatim** [comment]
I would point them to `[pitch.md](https://github.com/betatim/openscienceprize/blob/master/pitch.md)` and ask if they would be interested in seeing a live demo of this happen and if we can write in the proposal that we have an "acknowledgement of interest" from them.

**Comment by betatim** [comment]
I don't know either of these journals

**Comment by cranmer** [comment]
the first two are new, but aiming at open access. The second two are specifically looking at software (the first being new and open access, the second being ancient).

But all three are part of big publishing houses (Taylor and Francis, Elsevier)

**Comment by khinsen** [comment]
I'd say we should be as agnostic about journals as about repository hosting (see #27). On the other hand, we should be clear about going for openness.

Another community we should connect with is [Force11](http://www.force11.org/). Some publishers, including Elsevier, are represented there as well. I have a few contacts there, but perhaps others here as well.

**Comment by betatim** [comment]
Right now we are collecting interest from journals to big up the proposal. I think the people who have the contacts should decide if the journal is generally supportive of open science, open access, modern review techniques. I think it would look odd to have a journal known for its paywalls saying "yeah we like this idea" :smile: 

The journal aren't committing to using the solution, nor are we committing to delivering it to them.

**Comment by khinsen** [comment]
[Authorea](https://www.authorea.com/) is also working along these lines (integrating data and code into publications). I just saw the announcement of a seminar by one of its founders, whose abstract sounded strangely familiar.

**Comment by rougier** [comment]
@khinsen @ctb No need to say Rescience (rescience.github.io) coud greatly benefit from such effort.

**Comment by ctb** [comment]
On Thu, Feb 25, 2016 at 12:39:19AM -0800, Konrad Hinsen wrote:
> [Authorea](https://www.authorea.com/) is also working along these lines (integrating data and code into publications). I just saw the announcement of a seminar by one of its founders, whose abstract sounded strangely familiar.

Oh, that's a good idea! I don't know anyone in particular there, though.

**Comment by betatim** [comment]
I found this: https://www.authorea.com/users/23/articles/8762 where the authors discuss the paper of the future.

**Comment by khinsen** [comment]
Welcome @rougier! Yes, ReScience is an obvious client. But I don't think our support of the project matters much to potential funders. I hope that will change!

@ctb @betatim I will meet @apepe next week in Paris at his seminar. Too late for the proposal though.

**Comment by cranmer** [comment]
I’m friends with Alberto Pepe. Do we have any specific requests? Letter of support / commitment / collaboration?

**Comment by betatim** [comment]
@ctb penned this:
```
Would you be interested in this kind of thing? We're not signing you up for anything beyond saying "sure, that could be cool" but it'd be nice to show that there are some publishers interested in this kind of thing.
```
Which to me means that if they say yes we can list their name in the proposal as "these guys like the idea and support it".

**Comment by betatim** [comment]
Together with pointing them to the pitch.md in the repo.

**Comment by betatim** [comment]
The following are in:

* [x] [Giga](http://gigascience.biomedcentral.com/) Laurie Goodman
* [x] [F1000](http://F1000.com) Michael Markie
* [ ] <your journal/org here>

**Comment by khinsen** [comment]
Some [CiSE](http://www.computer.org/web/computingnow/cise) board members promised to look at this. Not sure there will be any good feedback before the deadline.

**Comment by betatim** [comment]
Nice. Let me know if they get back to you and I will update the list above. I contacted someone from opendata.cern.ch waiting for their reply.

**Comment by rougier** [comment]
I've aske PLOS Computational Biology, waiting for an answer.

**Comment by lyubomirpenev** [comment]
[Research Ideas and Outcomes](http://riojournal.com) (RIO) Journal is definitely interested to participate too. Contact name: Lyubomir Penev

**Comment by betatim** [comment]
:confetti_ball:

**Comment by khinsen** [comment]
It can't hurt to add [ReScience](https://rescience.github.io/) as well, even if it's not yet a glamour journal ;-)

**Comment by ctb** [comment]
This may also be relevant:

[Geoscience paper of the future](http://www.ontosoft.org/gpf/node/1)

**Comment by betatim** [comment]
@khinsen do you know someone at rescience/contacted them?

**Comment by rougier** [comment]
@betatim Konrad and me are chief-editors for ReScience... And we're very interested of course.

**Comment by betatim** [comment]
You don't plaster your names across https://rescience.github.io enough ;)

**Comment by ctb** [comment]
I'm on the ed board at ReScience, too ;).

**Comment by betatim** [comment]
This is going to look like an inside job!

**Comment by ctb** [comment]
:)

**Comment by betatim** [comment]
Reopening as we are still accumulating contacts. Updated comment above to include Gail Clement.
