### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by betatim** [everpub/openscienceprize#46]
I will submit the proposal at 10pm GMT+1 (Paris, Geneva) time. (The deadline for teams to submit entries for the Phase I prize is 11.59pm GMT on 29 February 2016)

**Deadline for changes 8pm GMT+1 (Paris, Geneva) time**
Anything not done by then will have to wait.

Bundle:
* `proposal.md` converted to PDF
* UI mockup
* `abstract.md` as plain text.

To be done:
* [x] **Abstract to be written** (= executive summary for submission, 300 words max)  
* [x] `team.md` to be completed (see #47)
* [x] Build the final PDF and review errors / glitches
 - [x] check #89 
* [x] Check length (current is ~16000 characters)

There are trailing comments in the proposal, I've listed them here just to be sure to not forget to process them before actual submission:
* [x] "many others (XXX more here)" to be completed or removed
* [x] "remote containers; (XXX more here)." to be completed or removed
* [x] "be addressed. (refs)" to be completed or removed
* [x] "this proposal (XXX)" to be removed ?
* [x] "and N people"  N = 7 ?
* [x] "place holder XXX" maybe it's time to remove it ?

**Comment by betatim** [comment]
(copying from #75)

**Comment by khinsen** [comment]
How about fixing a time for a "feature freeze"? After that, only cleanups (XXX etc.) and fixing typos. Don't know what's reasonable for our US friends - does 7 pm GMT sound fine? That leaves two hours to submission time for a final re-reading.

**Comment by rougier** [comment]
And we should start the abstract (or did I miss a PR?):
See https://www.openscienceprize.org/res/p/GFA/

```
An Executive Summary of the proposal suitable for an informed, lay 
audience and no longer than 300 words in length (see note below).

...

Please note that Executive Summaries for all applications will be shared
via the Open Science Prize website without exception and licensed
under the Creative Commons Attribution 4.0 License.  Applicants
should not include proprietary information in their Summary or any
other information they are not prepared to make openly available.
```

**Comment by betatim** [comment]
PR welcome!

**Comment by betatim** [comment]
Regarding the length, how do we treat all the hyperlinks?

Maybe the simplest option is to move all the blurbs about the team members to an extra file. We are allowed to submit up to three additional free-style files. We use one for the UI mockup.

**Comment by betatim** [comment]
Added a comment on feature freeze to the first comment in this issue.

**Comment by khinsen** [comment]
I'll propose an abstract in about 30 mn.

**Comment by rougier** [comment]
I was working on it...

**Comment by khinsen** [comment]
My abstract is in #82. Let's wait for @rougier's and synthesize!

**Comment by betatim** [comment]
Thoughts on moving the "Who we are" section to a separate file?

**Comment by rougier** [comment]
@khinsen Just read yours, way better than mine (which is not finished anyway). Will post to #82.

**Comment by khinsen** [comment]
@betatim Fine with me, though we should probably have some statement of the people behind the proposal in the main proposal text.

**Comment by betatim** [comment]
[proposal.pdf](https://github.com/betatim/openscienceprize/files/151032/proposal.pdf)

Attached the latest build of the proposal.

Right now thinking we should leave the people in the proposal.

**Comment by betatim** [comment]
We should probably remove the abstract from `proposal.md` and move it to `abstract.md`. I think the jury/readers will get given all the material so they won't get a proposal with no abstract attached. (If we leave it in we are seriously above character count)

**Comment by betatim** [comment]
Attaching rendered versions:

* [proposal.pdf](https://github.com/betatim/openscienceprize/files/151331/proposal.pdf)
* [proponents.pdf](https://github.com/betatim/openscienceprize/files/151330/proponents.pdf)
* [abstract.pdf](https://github.com/betatim/openscienceprize/files/151332/abstract.pdf)

Please post here if you find typos or bugs.

**Deadline for changes 8pm GMT+1 (Paris, Geneva) time**

After that time only serious, mega urgent, last minute fixes please.

We will submit `proposal.pdf`, `proponents.pdf`, and the [UI mockup](https://cloud.githubusercontent.com/assets/1448859/13301888/7217ff8a-db47-11e5-9c5a-51da4527821d.gif). The abstract will be submitted as plain text. The contents of `team.md` was used to fill in the submission form.

Stats:
```
proposal.md contains
   13295
characters
abstract.md contains
     300 abstract.md
words
```
The limit is 15k characters and 300 words respectively.

**Comment by betatim** [comment]
These are rendered versions of what is in 3bd6fc3.

Any embarrassing typos or outright torture of the English language?

Stats:
```
proposal.md contains
   15063
characters
abstract.md contains
     300 abstract.md
words
```

Tim feels a bit like travis, ...a robot should be doing this for me!

**Comment by betatim** [comment]
If we are :green_heart: to submit with plenty of time to spare, then we can update the links and move the repo.

**Comment by khinsen** [comment]
You say "these" - but where are the PDFs?

**Comment by betatim** [comment]
This is why a robot should be doing this! Sorry.

[proposal.pdf](https://github.com/betatim/openscienceprize/files/151669/proposal.pdf)
[abstract.pdf](https://github.com/betatim/openscienceprize/files/151670/abstract.pdf)
[proponents.pdf](https://github.com/betatim/openscienceprize/files/151671/proponents.pdf)

**Comment by khinsen** [comment]
LGTM but I think I have been reading all this too often to still be able to spot mistakes.

Of course #101 is still missing from this.

**Comment by rougier** [comment]
Very minor, but is there any reason for the `:` in section titles ?

**Comment by betatim** [comment]
Don't think so.

**Comment by betatim** [comment]
Took a stab at renaming all the links #108

**Comment by betatim** [comment]
Move completed. I'll start submitting using 1fd84839

**Comment by khinsen** [comment]
:fireworks:

**Comment by betatim** [comment]
Any final words before I push the big :radio_button: ?

**Comment by rougier** [comment]
May the Science be with you !

**Comment by cranmer** [comment]
:fireworks: :+1: :8ball:  ???

**Comment by ctb** [comment]
It's not due for a bit longer, right?

**Comment by betatim** [comment]
It is done now. The official deadline is at one minute before midnight GMT. I didn't want to stay up that long or risk their servers melting when people start uploading their 100MB video submission (oh yes, we could have shot a movie instead of all this writing!!)
