### ISSUE TITLE
Proponents

### ISSUE THREAD

**Issue by betatim** [everpub/openscienceprize#47]
I have to submit information about each team member. Please make a PR adding the below template (with your details) to `team.md` to get yourself added.

As this will be run as an open-source project you can participate independently of being a proponent.

Who can be a proponent? Anyone who thinks they contributed significantly to the proposal (commenting, editing, writing, connecting, ...) and who can make a commitment to continue working on this (aka has free brain cycles and time). [Some day, and that day will come, we will call upon you to do a service for the project](https://www.youtube.com/watch?v=DTtpWgrhS78). With open-source projects all the attractive topics get done quickly, the tedious and admin work gets done much more slowly. If you'd rather not have that kind of responsibility or have enough things cooking already, that is fine. The analogy for me is that a lot of people want to be an [Ironman](http://ironman.com/), but not many will do what it takes to be one.

I think we should find a way to give credit to all those that contributed (PRs, issues, and hypothes.is), I might start a `contributors.md` and list the names somewhere in `proposal.md`. Thoughts?

As always, if you disagree with this or have comments: let's discuss this.

------------
```
First Name:
Last Name:
Email Address:
Country of permanent address:
The Area of Expertise Contributing to Your Project:
Age: (you can prefer not to say)
Sex: (you can prefer not to say)
```
--------------------

**Comment by betatim** [comment]
Instead of using `contributors.md` add names of contributors to `LICENSE.md` after #59 gets merged.

**Comment by betatim** [comment]
Gentle reminder: If you don't add yourself to `team.md` with the above info I won't be able to add you as a proponent when I submit the proposal.

@ctb I still need a postal address from you.

**Comment by khinsen** [comment]
What does "The Area of Expertise Contributing to Your Project:" mean exactly? Who is the "you" in "your project"?

**Comment by betatim** [comment]
openscienceprize offers no guidance beyond this (it is just a webform). I assume the "your project" is referring to the proposal that is being submitted, so in this case "what is your expertise that is relevant to everpub".

**Comment by khinsen** [comment]
Ah, thanks. I hadn't realized this was the wording from the Open Science Prize forms.

**Comment by ctb** [comment]
On Sun, Feb 28, 2016 at 12:10:56PM -0800, Tim Head wrote:
> Gentle reminder: If you don't add yourself to `team.md` with the above info I won't be able to add you as a proponent when I submit the proposal.
> 
> @ctb I still need a postal address from you.

@betat

C. Titus Brown
VM: PHR
1 Shields Ave
Davis, CA 95616
